In [15]:
import cv2
from PIL import Image
import tempfile
import numpy as np
from textblob import TextBlob
from wordcloud import WordCloud, STOPWORDS 
import matplotlib.pyplot as plt 
import pandas as pd 
import smtplib
from gtts import gTTS 
import os
import numpy

In [2]:
import imutils #resize reshaping cropping fedd from camera

import time
import os #to handle directories

In [8]:
algorithm=r"C:\Users\91759\Desktop\project-set-2\pantech\haarcascade_frontalface_default.xml"

haarcscade=cv2.CascadeClassifier(algorithm)

# Creating Dataset

In [13]:
dataset="classifierdataset"
name="subh"
path=os.path.join(dataset,name)
if not os.path.isdir(path):  #checking a directory exist or not
    os.makedirs(path)

In [14]:
cam=cv2.VideoCapture(0)
(width,height)=(130,100)
count=1
while count<31:
    
    _,img=cam.read()
    gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=haarcscade.detectMultiScale(gray_image,1.3,4) #detdct co-ordinates
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
        onlyFace=gray_image[y:y+h,x:x+w]
        resize_img=cv2.resize(onlyFace,(width,height))
        cv2.imwrite("%s/%s.jpg"%(path,count),resize_img)
        count+=1
    cv2.imshow("Face_detection",img)
    key=cv2.waitKey(10)
    
    if key==27:
         break
print("face_captured")
cam.release()    
cv2.destroyAllWindows()

face_captured


# Face Recognition

In [29]:
#subh,name-labels
#imasges name 1.jpg 2.jpg is names
#id(0) 1st flder name
(images,labels,names,id)=([],[],{},0)
#subdirs is named as classiferdatsets
#dirs is folder named as subhash etc
#files is named as 1,2,3,4,5.jpg
for (subdirs,dirs,files) in os.walk(dataset):
    for subdirs in dirs:
        names[id]=subdirs
        subjectpath=os.path.join(dataset,subdirs)
        for filename in os.listdir(subjectpath):
            paths=subjectpath+'/'+filename
            label=id
            images.append(cv2.imread(paths,0))
            labels.append(int(label))
        id+=1
(width,height)=(130,100)
(images,labels)=[numpy.array(lis) for lis in [images,labels] ]
print(images,labels)            

#30 images array plus label 0 1


[[[102 105 102 ...  23  12   5]
  [102  98 100 ...  25  19   6]
  [101  96  89 ...  28  26   8]
  ...
  [ 33  30  27 ...  24  22  21]
  [ 37  33  29 ...  30  25  25]
  [ 40  35  31 ...  33  28  28]]

 [[107 105 107 ...  10   9   9]
  [104 102 100 ...   6   3   4]
  [107 106 103 ...   6   7   7]
  ...
  [ 62  75  78 ...  90  55  34]
  [ 67  68  66 ... 127 126 112]
  [ 55  51  46 ... 130 130 131]]

 [[ 97  94  69 ...   1   2   1]
  [100  85  60 ...   0   5   5]
  [ 92  59  34 ...   6   5   5]
  ...
  [ 26  26  27 ...  22  15  11]
  [ 24  24  25 ...  22  14  11]
  [ 22  22  23 ...  22  12   9]]

 ...

 [[ 52  51  50 ...  50  50  50]
  [ 46  47  48 ...  49  49  49]
  [ 39  39  39 ...  49  50  50]
  ...
  [ 26  25  23 ...  27  28  29]
  [ 17  17  15 ...  29  31  32]
  [ 12  12  11 ...  29  32  33]]

 [[ 53  54  54 ...  46  49  50]
  [ 55  55  54 ...  47  49  49]
  [ 49  51  52 ...  48  49  49]
  ...
  [ 26  27  28 ...  22  24  25]
  [ 15  16  18 ...  23  24  25]
  [ 11  12  13 ...  25  27  

# Model Classifier

In [34]:
model=cv2.face.LBPHFaceRecognizer_create()
#model=cv2.face.FisherFaceRecognizer_create()

In [35]:
model.train(images,labels)
print("training completed")

training completed


# Face Detection

In [39]:
cam=cv2.VideoCapture(0)
(width,height)=(130,100)
count=1
while count<31:
    
    _,img=cam.read()
    gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=haarcscade.detectMultiScale(gray_image,1.3,4) #detdct co-ordinates
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
        onlyFace=gray_image[y:y+h,x:x+w]
        resize_img=cv2.resize(onlyFace,(width,height))
        prediction=model.predict(resize_img)
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
        if prediction[1]<800:
            cv2.putText(img,"%s - %.0f"%(names[prediction[0]],prediction[1]),
                       (x-20,y-10),cv2.FONT_HERSHEY_PLAIN,2,(0,255,0))
            print(names[prediction[0]])
            count=0
        else:
            count+=1
            cv2.putText(img,"Unknown",
                       (x-20,y-10),cv2.FONT_HERSHEY_PLAIN,2,(0,255,0))
            if(count>100):
                print("Unknown Person")
                cv2.imwrite("Input.jpg",img)
                count=0
    cv2.imshow("OpenCV",img)
    key=cv2.waitKey(10)
    if key==27:
        break
cam.release()
cv2.destroyAllWindows()

            
            

Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
subh
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
Name
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
subh
